---
  - name: clickhouse-role
    src: git@github.com:antigen2/clickhouse-role.git
    scm: git
    version: "1.0.0"
  - name: vector-role
    src: git@github.com:antigen2/vector-role.git
    scm: git
    version: "1.0.0"
  - name: lighthouse-role
    src: git@github.com:antigen2/lighthouse-role.git
    scm: git
    version: "1.0.0"
